import { MigrationInterface, QueryRunner } from "typeorm";

export class MigrationName1763845619872 implements MigrationInterface {
    name = 'MigrationName1763845619872'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_team_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "campaigns_ad_source_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "campaigns_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "leads_campaign_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "leads_owner_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "leads_assigned_to_fkey"`);
        await queryRunner.query(`ALTER TABLE "price_offers" DROP CONSTRAINT "price_offers_lead_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "price_offers" DROP CONSTRAINT "price_offers_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP CONSTRAINT "deals_lead_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP CONSTRAINT "deals_pipeline_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP CONSTRAINT "deals_stage_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "stages" DROP CONSTRAINT "stages_pipeline_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "messages_lead_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP CONSTRAINT "meetings_lead_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP CONSTRAINT "meetings_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "lead_notes" DROP CONSTRAINT "lead_notes_lead_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "lead_notes" DROP CONSTRAINT "lead_notes_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP CONSTRAINT "integrations_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "files_lead_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "files_uploaded_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "activities_lead_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "activities_user_id_fkey"`);
        await queryRunner.query(`CREATE TABLE "twilio_settings" ("id" SERIAL NOT NULL, "account_sid" character varying NOT NULL, "auth_token" character varying NOT NULL, "phone_number" character varying, "webhook_url" character varying, "active" boolean NOT NULL DEFAULT true, "user_id" integer, "created_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_675dff35bfb22f20b91205e83ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "landing_pages" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "slug" character varying, "content" text, "template" character varying, "settings" jsonb NOT NULL DEFAULT '{}', "sections" jsonb NOT NULL DEFAULT '[]', "active" boolean NOT NULL DEFAULT true, "description" character varying, "campaign_id" integer, "created_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_962a8e504985c1488c7e43c7791" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tiktok_integrations" ("id" SERIAL NOT NULL, "access_token" character varying, "refresh_token" character varying, "expires_at" TIMESTAMP, "user_id" integer, "advertiser_ids" jsonb, "app_id" character varying, "secret" character varying, "active" boolean NOT NULL DEFAULT true, "created_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_59e487582a130d5c26161f57763" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "websites" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "url" character varying, "api_key" character varying, "auth_token" character varying, "endpoint_url" character varying, "created_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da80e50ae0d986d43c9eb80ab70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dashboard_accounts" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "email" character varying, "api_key" character varying, "refresh_token" character varying, "expires_at" TIMESTAMP, "active" boolean NOT NULL DEFAULT true, "created_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e82e1b93918eba563aa7a9bd7a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "actor_user_id" integer, "entity" character varying NOT NULL, "entity_id" integer, "action" character varying NOT NULL, "diff_json" json, "at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ad_spend" ("id" SERIAL NOT NULL, "campaign_id" integer, "date" date NOT NULL, "spend" numeric(10,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7166800438768e6edc30571af2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lead_touchpoints_event_type_enum" AS ENUM('view', 'submit')`);
        await queryRunner.query(`CREATE TABLE "lead_touchpoints" ("id" SERIAL NOT NULL, "lead_id" integer, "campaign_id" integer, "event_type" "public"."lead_touchpoints_event_type_enum" NOT NULL, "campaign_name" character varying, "ip_address" character varying, "country" character varying, "user_agent" character varying, "additional_data" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_00418958df5fa90db2c3f1f63fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD "user_id" integer`);
        await queryRunner.query(`CREATE TYPE "public"."integrations_type_enum" AS ENUM('oauth', 'webhook', 'api', 'wordpress')`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD "type" "public"."integrations_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."integrations_status_enum" AS ENUM('active', 'inactive', 'error', 'connected')`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD "status" "public"."integrations_status_enum" DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD "page_access_token" character varying`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD "user_access_token" character varying`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD "scopes" jsonb`);
        await queryRunner.query(`CREATE TYPE "public"."integrations_webhook_status_enum" AS ENUM('active', 'inactive', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD "webhook_status" "public"."integrations_webhook_status_enum"`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD "auth_token" character varying`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "budget" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "cost_per_lead" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "lead_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."leads_status_enum" RENAME TO "leads_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leads_status_enum" AS ENUM('new', 'contacted', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost', 'archived')`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "status" TYPE "public"."leads_status_enum" USING "status"::"text"::"public"."leads_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "status" SET DEFAULT 'new'`);
        await queryRunner.query(`DROP TYPE "public"."leads_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."lead_source_enum" RENAME TO "lead_source_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leads_source_enum" AS ENUM('manual', 'meta', 'tiktok', 'landing_page', 'wordpress', 'import', 'api')`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "source" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "source" TYPE "public"."leads_source_enum" USING "source"::"text"::"public"."leads_source_enum"`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "source" SET DEFAULT 'manual'`);
        await queryRunner.query(`DROP TYPE "public"."lead_source_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "source" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "custom_fields" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "raw_payload" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "currency" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."price_offer_status_enum" RENAME TO "price_offer_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."price_offers_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'expired')`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "status" TYPE "public"."price_offers_status_enum" USING "status"::"text"::"public"."price_offers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."price_offer_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deals" ALTER COLUMN "won" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."messages_channel_enum" RENAME TO "messages_channel_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."messages_channel_enum" AS ENUM('whatsapp', 'sms', 'email')`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "channel" TYPE "public"."messages_channel_enum" USING "channel"::"text"::"public"."messages_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."messages_channel_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."messages_direction_enum" RENAME TO "messages_direction_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."messages_direction_enum" AS ENUM('in', 'out', 'out', 'in')`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "direction" TYPE "public"."messages_direction_enum" USING "direction"::"text"::"public"."messages_direction_enum"`);
        await queryRunner.query(`DROP TYPE "public"."messages_direction_enum_old"`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "timestamp" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "duration" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP COLUMN "participants"`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD "participants" character varying`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."meetings_status_enum" RENAME TO "meetings_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."meetings_status_enum" AS ENUM('scheduled', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" TYPE "public"."meetings_status_enum" USING "status"::"text"::"public"."meetings_status_enum"`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "public"."meetings_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lead_notes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."integration_provider_enum" RENAME TO "integration_provider_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."integrations_provider_enum" AS ENUM('facebook', 'meta', 'tiktok', 'google', 'wordpress', 'api')`);
        await queryRunner.query(`ALTER TABLE "integrations" ALTER COLUMN "provider" TYPE "public"."integrations_provider_enum" USING "provider"::"text"::"public"."integrations_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."integration_provider_enum_old"`);
        await queryRunner.query(`ALTER TABLE "integrations" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."files_type_enum" RENAME TO "files_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."files_type_enum" AS ENUM('contract', 'proposal', 'invoice', 'receipt', 'other')`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "type" TYPE "public"."files_type_enum" USING "type"::"text"::"public"."files_type_enum"`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "type" SET DEFAULT 'other'`);
        await queryRunner.query(`DROP TYPE "public"."files_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "uploaded_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."activity_type_enum" RENAME TO "activity_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."activities_type_enum" AS ENUM('call', 'email', 'meeting', 'note', 'task')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" TYPE "public"."activities_type_enum" USING "type"::"text"::"public"."activities_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1208ee1db5ddb64b48a86b46a61" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "twilio_settings" ADD CONSTRAINT "FK_4f7541fc627db3ea6bbbea97243" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "FK_fbd44afe82b9bc8d24b12c00d94" FOREIGN KEY ("ad_source_id") REFERENCES "ad_sources"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "FK_49da41a196c3d2bd6f5ce1dc3b5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_cdae2f7bc00b25eb3f22d4082b5" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_a9cf4831fe470977849db2c97ac" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_5c37aa54e3b06f6733d56007e0c" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_offers" ADD CONSTRAINT "FK_9dca64f14971400f579f0114868" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_offers" ADD CONSTRAINT "FK_98430d552ee79cafe1e65cdcb6f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deals" ADD CONSTRAINT "FK_96b51475f76f01c135ecdc968dc" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deals" ADD CONSTRAINT "FK_9e8ce2b9d84c7fb97105ce7f007" FOREIGN KEY ("pipeline_id") REFERENCES "pipelines"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deals" ADD CONSTRAINT "FK_23f5265469e4b4daea988d91465" FOREIGN KEY ("stage_id") REFERENCES "stages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stages" ADD CONSTRAINT "FK_ea5edc95a1956539edaa4b7e5e7" FOREIGN KEY ("pipeline_id") REFERENCES "pipelines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_5cba80c8f9b3fa687a0dff75736" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD CONSTRAINT "FK_b6b8deb8ba2095ffc2c1ed02337" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD CONSTRAINT "FK_be6ff3e68963349ea42cf55319e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_notes" ADD CONSTRAINT "FK_724573b69882525ab16b174101d" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_notes" ADD CONSTRAINT "FK_d10c241000af13a1b4273256ab5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "landing_pages" ADD CONSTRAINT "FK_10a188aff111e9f85cf47b75675" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "landing_pages" ADD CONSTRAINT "FK_2c6c7627d3df7bccacbd58f63a5" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD CONSTRAINT "FK_164ca953d754a486cb1e404fadb" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tiktok_integrations" ADD CONSTRAINT "FK_13837fedc52584a59b7dcfa0ae4" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "websites" ADD CONSTRAINT "FK_4470ed544160ca7f543803a4bbc" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_140e8506ddd42ed073d8d3c2d24" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dashboard_accounts" ADD CONSTRAINT "FK_67e901846b7a3c349b29cd2b8a3" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_f160d97a931844109de9d04228f" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_spend" ADD CONSTRAINT "FK_0fe89c45c86d16d95ef65cbf5df" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_df9eae372b2fdd0e4fb74871667" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_b82f1d8368dd5305ae7e7e664c2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_touchpoints" ADD CONSTRAINT "FK_c3ae5f14e5ba816ea8dcc12862e" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_touchpoints" ADD CONSTRAINT "FK_a7ea504a248ac23a8818b748f44" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "lead_touchpoints" DROP CONSTRAINT "FK_a7ea504a248ac23a8818b748f44"`);
        await queryRunner.query(`ALTER TABLE "lead_touchpoints" DROP CONSTRAINT "FK_c3ae5f14e5ba816ea8dcc12862e"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_b82f1d8368dd5305ae7e7e664c2"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_df9eae372b2fdd0e4fb74871667"`);
        await queryRunner.query(`ALTER TABLE "ad_spend" DROP CONSTRAINT "FK_0fe89c45c86d16d95ef65cbf5df"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_f160d97a931844109de9d04228f"`);
        await queryRunner.query(`ALTER TABLE "dashboard_accounts" DROP CONSTRAINT "FK_67e901846b7a3c349b29cd2b8a3"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_140e8506ddd42ed073d8d3c2d24"`);
        await queryRunner.query(`ALTER TABLE "websites" DROP CONSTRAINT "FK_4470ed544160ca7f543803a4bbc"`);
        await queryRunner.query(`ALTER TABLE "tiktok_integrations" DROP CONSTRAINT "FK_13837fedc52584a59b7dcfa0ae4"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP CONSTRAINT "FK_164ca953d754a486cb1e404fadb"`);
        await queryRunner.query(`ALTER TABLE "landing_pages" DROP CONSTRAINT "FK_2c6c7627d3df7bccacbd58f63a5"`);
        await queryRunner.query(`ALTER TABLE "landing_pages" DROP CONSTRAINT "FK_10a188aff111e9f85cf47b75675"`);
        await queryRunner.query(`ALTER TABLE "lead_notes" DROP CONSTRAINT "FK_d10c241000af13a1b4273256ab5"`);
        await queryRunner.query(`ALTER TABLE "lead_notes" DROP CONSTRAINT "FK_724573b69882525ab16b174101d"`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP CONSTRAINT "FK_be6ff3e68963349ea42cf55319e"`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP CONSTRAINT "FK_b6b8deb8ba2095ffc2c1ed02337"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_5cba80c8f9b3fa687a0dff75736"`);
        await queryRunner.query(`ALTER TABLE "stages" DROP CONSTRAINT "FK_ea5edc95a1956539edaa4b7e5e7"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP CONSTRAINT "FK_23f5265469e4b4daea988d91465"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP CONSTRAINT "FK_9e8ce2b9d84c7fb97105ce7f007"`);
        await queryRunner.query(`ALTER TABLE "deals" DROP CONSTRAINT "FK_96b51475f76f01c135ecdc968dc"`);
        await queryRunner.query(`ALTER TABLE "price_offers" DROP CONSTRAINT "FK_98430d552ee79cafe1e65cdcb6f"`);
        await queryRunner.query(`ALTER TABLE "price_offers" DROP CONSTRAINT "FK_9dca64f14971400f579f0114868"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_5c37aa54e3b06f6733d56007e0c"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_a9cf4831fe470977849db2c97ac"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_cdae2f7bc00b25eb3f22d4082b5"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "FK_49da41a196c3d2bd6f5ce1dc3b5"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "FK_fbd44afe82b9bc8d24b12c00d94"`);
        await queryRunner.query(`ALTER TABLE "twilio_settings" DROP CONSTRAINT "FK_4f7541fc627db3ea6bbbea97243"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1208ee1db5ddb64b48a86b46a61"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."activity_type_enum_old" AS ENUM('call', 'message', 'meeting', 'note')`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "type" TYPE "public"."activity_type_enum_old" USING "type"::"text"::"public"."activity_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."activities_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."activity_type_enum_old" RENAME TO "activity_type_enum"`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "uploaded_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "type" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."files_type_enum_old" AS ENUM('image', 'document', 'other')`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "type" TYPE "public"."files_type_enum_old" USING "type"::"text"::"public"."files_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "type" SET DEFAULT 'other'`);
        await queryRunner.query(`DROP TYPE "public"."files_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."files_type_enum_old" RENAME TO "files_type_enum"`);
        await queryRunner.query(`ALTER TABLE "integrations" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."integration_provider_enum_old" AS ENUM('meta', 'tiktok', 'wordpress', 'google_ads', 'custom')`);
        await queryRunner.query(`ALTER TABLE "integrations" ALTER COLUMN "provider" TYPE "public"."integration_provider_enum_old" USING "provider"::"text"::"public"."integration_provider_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_provider_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."integration_provider_enum_old" RENAME TO "integration_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "lead_notes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."meetings_status_enum_old" AS ENUM('scheduled', 'done', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" TYPE "public"."meetings_status_enum_old" USING "status"::"text"::"public"."meetings_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "public"."meetings_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."meetings_status_enum_old" RENAME TO "meetings_status_enum"`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP COLUMN "participants"`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD "participants" text`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "duration" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "timestamp" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."messages_direction_enum_old" AS ENUM('incoming', 'outgoing')`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "direction" TYPE "public"."messages_direction_enum_old" USING "direction"::"text"::"public"."messages_direction_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."messages_direction_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."messages_direction_enum_old" RENAME TO "messages_direction_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."messages_channel_enum_old" AS ENUM('whatsapp', 'sms', 'email', 'call')`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "channel" TYPE "public"."messages_channel_enum_old" USING "channel"::"text"::"public"."messages_channel_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."messages_channel_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."messages_channel_enum_old" RENAME TO "messages_channel_enum"`);
        await queryRunner.query(`ALTER TABLE "deals" ALTER COLUMN "won" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."price_offer_status_enum_old" AS ENUM('pending', 'accepted', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "status" TYPE "public"."price_offer_status_enum_old" USING "status"::"text"::"public"."price_offer_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."price_offers_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."price_offer_status_enum_old" RENAME TO "price_offer_status_enum"`);
        await queryRunner.query(`ALTER TABLE "price_offers" ALTER COLUMN "currency" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "raw_payload" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "custom_fields" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "source" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."lead_source_enum_old" AS ENUM('manual', 'meta', 'tiktok', 'google_ads', 'landing_page', 'wordpress', 'api')`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "source" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "source" TYPE "public"."lead_source_enum_old" USING "source"::"text"::"public"."lead_source_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "source" SET DEFAULT 'manual'`);
        await queryRunner.query(`DROP TYPE "public"."leads_source_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."lead_source_enum_old" RENAME TO "lead_source_enum"`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."leads_status_enum_old" AS ENUM('new', 'in_progress', 'follow_up', 'not_answering', 'closed', 'won', 'lost')`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "status" TYPE "public"."leads_status_enum_old" USING "status"::"text"::"public"."leads_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "status" SET DEFAULT 'new'`);
        await queryRunner.query(`DROP TYPE "public"."leads_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."leads_status_enum_old" RENAME TO "leads_status_enum"`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "lead_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "cost_per_lead" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "budget" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "campaigns" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP COLUMN "auth_token"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP COLUMN "webhook_status"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_webhook_status_enum"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP COLUMN "scopes"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP COLUMN "user_access_token"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP COLUMN "page_access_token"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_type_enum"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP COLUMN "user_id"`);
        await queryRunner.query(`DROP TABLE "lead_touchpoints"`);
        await queryRunner.query(`DROP TYPE "public"."lead_touchpoints_event_type_enum"`);
        await queryRunner.query(`DROP TABLE "ad_spend"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "dashboard_accounts"`);
        await queryRunner.query(`DROP TABLE "websites"`);
        await queryRunner.query(`DROP TABLE "tiktok_integrations"`);
        await queryRunner.query(`DROP TABLE "landing_pages"`);
        await queryRunner.query(`DROP TABLE "twilio_settings"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "activities_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "activities_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "files_uploaded_by_fkey" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "files_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD CONSTRAINT "integrations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_notes" ADD CONSTRAINT "lead_notes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_notes" ADD CONSTRAINT "lead_notes_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD CONSTRAINT "meetings_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD CONSTRAINT "meetings_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "messages_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stages" ADD CONSTRAINT "stages_pipeline_id_fkey" FOREIGN KEY ("pipeline_id") REFERENCES "pipelines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deals" ADD CONSTRAINT "deals_stage_id_fkey" FOREIGN KEY ("stage_id") REFERENCES "stages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deals" ADD CONSTRAINT "deals_pipeline_id_fkey" FOREIGN KEY ("pipeline_id") REFERENCES "pipelines"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deals" ADD CONSTRAINT "deals_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_offers" ADD CONSTRAINT "price_offers_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_offers" ADD CONSTRAINT "price_offers_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "leads_assigned_to_fkey" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "leads_owner_user_id_fkey" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "leads_campaign_id_fkey" FOREIGN KEY ("campaign_id") REFERENCES "campaigns"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_ad_source_id_fkey" FOREIGN KEY ("ad_source_id") REFERENCES "ad_sources"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
